### ISSUE TITLE
Point defender doesn't show up when someone votes 0

### ISSUE THREAD

**Issue by BearAlliance** [BearAlliance/pointing-poker#37]
<img width="1044" alt="Screen Shot 2020-03-26 at 9 10 24 PM" src="https://user-images.githubusercontent.com/8557692/77711063-4a4c7380-6fa6-11ea-8274-8849e4260677.png">
<img width="1045" alt="Screen Shot 2020-03-26 at 9 10 19 PM" src="https://user-images.githubusercontent.com/8557692/77711067-4c163700-6fa6-11ea-91a5-637f7d7079fc.png">

**Comment by sartechb** [comment]
Why do we allow for a 0 vote?

**Comment by BearAlliance** [comment]
Good point. I would imagine 0 is "already done" but that sounds pretty silly. It's a legitimate vote in most poker guides, but I don't see a huge need for it at this moment.

Maybe we solve this by just removing the "0" button?

**Comment by sartechb** [comment]
I think I would prefer an 'idk' button or a '?' if you really don't know how much the points should be without giving it like an 8 or 13 y'know?

**Comment by BearAlliance** [comment]
Yup makes sense. We can fix it for now by removing the 0. Adding a "?" would complicate the min/max/average calculations so that's a good candidate for a different enhancement

**Comment by olore** [comment]
oh you made a PR already, oopsie
