### ISSUE TITLE
Disallow concurrent story title editing

### ISSUE THREAD

**Issue by BearAlliance** [BearAlliance/pointing-poker#44]
To prevent concurrency issues.

Not 100% sure we need this at this point

**Comment by olore** [comment]
I kinda like it as is. It let's you rotate who is "(re)setting the story" following a vote. More importantly if someone is falling asleep, anyone can just take over.

**Comment by BearAlliance** [comment]
Good points. I haven't seen a problem with it in the tests we've done so I think it's fine as is.

Closing until it becomes a problem
